package com.kk.webservice.JAXWSExamples;

import com.kk.webservices.hellowebserviceclient.HelloInterface;
import com.kk.webservices.hellowebserviceclient.HelloWebServiceName;

//This class calls the Hello web service defined in HelloWS1.java
//The client classes present in com.kk.webservices.hellowebserviceclient package for this WSDL were generated by wsimport command line utility
//Below is command line for wsimport - 
//wsimport -verbose -d gen -extension -keep http://localhost:9998/hello?wsdl
public class Example_3 {

	public static void main(String[] args) {
		HelloWebServiceName service = new HelloWebServiceName();
		HelloInterface helloInterface = service.getHelloWebSvcPort();
		String result = helloInterface.sayHello("KK");
		System.out.println(result);
	}

}
