package com.kk.webservice.SAAJExamples;

import net.webservicex.StockQuote;
import net.webservicex.StockQuoteSoap;

//This class calls the StockQuote web service hosted by Webservicesx.net website
// The client classes present in net.webservicex package for this WSDL were generated by wsimport command line utility
//Below is command line for wsimport - 
// wsimport -verbose -d gen -extension -keep http://www.webservicex.net/stockquote.asmx?WSDL
public class Example3 {

	public static void main(String[] args) {
		System.out.println("Invoking.....");
		StockQuote service = new StockQuote();
		StockQuoteSoap port = service.getStockQuoteSoap();
		String stockInfo = port.getQuote("sun");
		System.out.println("Printing stock info for Sun Microsystems");
		System.out.println(stockInfo);
	}

}
