
package com.kk.webservice.hellowebserviceclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloInterface1", targetNamespace = "http://HelloWebServiceClient.webservice.kk.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloInterface1 {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://HelloWebServiceClient.webservice.kk.com", className = "com.kk.webservice.hellowebserviceclient.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://HelloWebServiceClient.webservice.kk.com", className = "com.kk.webservice.hellowebserviceclient.SayHelloResponse")
    @Action(input = "http://HelloWebServiceClient.webservice.kk.com/HelloInterface1/sayHelloRequest", output = "http://HelloWebServiceClient.webservice.kk.com/HelloInterface1/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
